name: Deploy Lambda Function

run-name: Lambda Function Deployment ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches: [development, testing, release]
    paths-ignore:
      - ".github/**"
      - ".test/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install AWS CLI
        run: pip install awscli

      - name: Package Lambda Function
        run: |
          zip function.zip lambda_function.py
          echo "Lambda function packaged successfully."

      - name: Deploy Lambda Function
        run: |
          FUNCTION_NAME=${{ vars.LAMBDA_FUNCTION_NAME }}
          ZIP_FILE=function.zip
          
          # Check if the function exists
          aws lambda get-function --function-name $FUNCTION_NAME || FUNCTION_NOT_FOUND=true
          
          if [ "$FUNCTION_NOT_FOUND" = true ]; then
            # Create the Lambda function if it doesn't exist
            aws lambda create-function \
              --function-name $FUNCTION_NAME \
              --runtime python3.8 \
              --role ${{ secrets.LAMBDA_EXECUTION_ROLE }} \
              --handler lambda_function.lambda_handler \
              --zip-file fileb://$ZIP_FILE
          else
            # Update the Lambda function if it exists
            aws lambda update-function-code \
              --function-name $FUNCTION_NAME \
              --zip-file fileb://$ZIP_FILE
          fi
