name: Deploy Windows Server to Azure

run-name: Windows Server VM ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches: [development, testing, main]
    paths-ignore:
      - ".github/**"
      - ".test/**"
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy VM
        env:
          RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
          LOCATION: ${{ vars.LOCATION }}
          VM_NAME: ${{ vars.VM_NAME }}
          VNET_NAME: ${{ vars.VNET_NAME }}
          SUBNET_NAME: ${{ vars.SUBNET_NAME }}
          NIC_NAME: ${{ vars.NIC_NAME }}
          ADMIN_USERNAME: ${{ vars.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          IMAGE: ${{ vars.IMAGE }}
        run: bash deploy-vm.sh
        uses: steebchen/kubectl@v2.0.0
        with:
          args: set image -f k8s/deployment.yaml ${CONTAINER_NAME}=$ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_TAG }} --kubeconfig /tmp/.kube/config
          # config: ${{ secrets.KUBE_CONFIG_DATA }}
